### ISSUE TITLE
Warning: Cannot read property 'execute' of undefined Use --force to continue.

### ISSUE THREAD

**Issue by tim545** [iancmyers/eslint-grunt#9]
I started getting this error recently when running this task - "Warning: Cannot read property 'execute' of undefined Use --force to continue." 

I noticed that eslint has updated 3 days ago and though it could be the cause of the issue?

**Comment by pkosenko** [comment]
Yes, this seems to be the same problem I was having earlier in the week.  After scratching my head and wondering "What did I do wrong?" I discovered that the most recent update of ESLint is no longer working with various grunt loaders.  Check out these references:

https://github.com/elastic/kibana/issues/4558
https://github.com/gyandeeps/gruntify-eslint/issues/9

I managed to get ESLint working again with grunt using the "gruntify-eslint" Node module.  Other grunt eslint loaders don't seem to have been fixed yet.

https://github.com/gyandeeps/gruntify-eslint

**Comment by tim545** [comment]
Yeah, that was the same conclusion I came to as well, actually I didn't see the package you used but I made a clone of this one and locked the eslint version to latest one it worked with, which was 0.24.1

https://www.npmjs.com/package/eslint-grunt-dep-locked

I only did this as a quick solution though because I needed to keep working at the time, the better thing to do of course would be to submit a PR to this project...

**Comment by pkosenko** [comment]
Yes, I think a patch request to this package would be in order.  I haven't yet had a chance to look into the actual module code to see what is making the other "gruntify-eslint" work with the latest eslint, but that would be a good place to start.
On the other hand, your solution may help you avoid having to update a lot of eslint rules.  The latest eslint is going to force you to change a lot of settings in your .eslintrc file(s).

**Comment by mhawila** [comment]
I am having the same issue in August 9th, 2016 using version 1.0.0. Was this issue ever fixed? @pkosenko & @tim545

**Comment by monochrome-yeh** [comment]
the same as issue to me.

**Comment by createdbyjurand** [comment]
the same

**Comment by ylerjen** [comment]
same here...

**Comment by tim545** [comment]
No sorry guys looks like no updates have happened, I think the best option would be to just use `grunt-eslint` which is really the same thing and it looks like it supports the latest version of eslint. If for some reason your working on an old project that you want and old version of eslint for then that package I added years ago still runs off 0.24.1 but I doubt many people will have any need for that now.

I might close this issue so it doesn't sit here and cause confusion for people...
